"""empty message

Revision ID: 2d87af47ae72
Revises: c9498c36f908
Create Date: 2021-10-01 16:23:34.352888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d87af47ae72'
down_revision = 'c9498c36f908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('show_veune_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.drop_column('show', 'veune_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('veune_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_veune_id_fkey', 'show', 'venue', ['veune_id'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
